"""Base Protocol that all LLM providers must satisfy."""
from __future__ import annotations
from typing import Protocol, runtime_checkable


@runtime_checkable
class LLMClient(Protocol):
    async def chat(self, messages: list[dict], *, json_mode: bool = False, **kwargs) -> str: ...
    async def chat_json(self, system: str, user: str, **kwargs) -> dict: ...
    async def vision(self, prompt: str, image_bytes: bytes, **kwargs) -> str: ...
    async def vision_json(self, prompt: str, image_bytes: bytes, **kwargs) -> dict: ...
    async def embed(self, text: str) -> list[float]: ...
    async def close(self) -> None: ...
